# vim: ft=yaml
---
driver: docker

driver_config:
  use_sudo: false
  privileged: true
  provision_command: mkdir -p /run/sshd
  run_command: /lib/systemd/systemd

provisioner:
  name: salt_solo
  salt_install: bootstrap
  formula: gitlab_omnibus
  state_top:
    base:
      "*":
        - gitlab_omnibus
platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04

verifier:
  name: inspec
  sudo: true
  reporter:
    - cli

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    provisioner:
      pillars_from_files:
        gitlab_omnibus.sls: pillar.example
      pillars:
        top.sls:
          base:
            '*':
              - gitlab_omnibus
